<?php
/**
 * @var $name
 * @var $surname
 * @var $logo_path
 * @var $date_time_purchase
 * @var $ids
 * @var $zone
 * @var $type
 * @var $quantity
 * @var $price
 */
?>
<?php $this->layout('home', ['title' => 'result']); ?>
<br><h3>total price: <?php echo number_format($price*$quantity, 2)?>€</h3><br>
<div class="columns">
	<?php for ($i = 0; $i < $quantity; $i++) { ?>
      <div class="column">
          <table class="table table-striped table-hover">
              <tbody>
              <tr>
                  <td>logo</td><td><img src=<?= $logo_path ?> class="img-responsive"></td>
              </tr><tr>
                  <td>name</td><td><?= $surname ?> <?= $name ?></td>
              </tr><tr>
                  <td>date</td><td><?= $date_time_purchase ?></td>
              </tr><tr>
                  <td>price</td><td><?= $price ?></td>
              </tr><tr>
                  <td>zone</td><td><?= $zone ?></td>
              </tr><tr>
                  <td>type</td><td><?= $type ?></td>
              </tr><tr>
                  <td>id</td><td><?= $ids[$i] ?></td>
              </tr>
              </tbody>
          </table>
      </div>
	<?php } ?>
</div>
